### ISSUE TITLE
Question about Nightly toolchain abolishment

### ISSUE THREAD

**Issue by shunsukew** [paritytech/srtool#62]
<img width="1108" alt="Screen Shot 2023-05-02 at 16 19 45" src="https://user-images.githubusercontent.com/28953860/235603998-c952e892-0094-433c-84a9-88c9b0ffdc70.png">
After the latest release https://github.com/paritytech/srtool/releases/tag/v0.10.0, srtool build start to fail because we're using nightly only feature inside our code. Is there any reason toolchain was changed to stable, and do we have an option to use nightly instead?

**Comment by chevdor** [comment]
Using nightly is in general not advised. It was done until recently since we had no other choice.

Now that using stable is possible, `srtool` does that by default and I would suggest checking out your option to not require nightlies.

If you want to stick to nightlies for now, there are a few options:
- use the previous release of srtool (you will have to specifiy only the version and **not** let the `srtool-actions` pick it for you)
- build a nightly version of srtool, there is a single line to uncomment, I can point it out if you want to go this route

I would recommend the first option for now and get rid of the nightlies dependencies asap.

**Comment by shunsukew** [comment]
I see, thank you for your answering.
In that case, we're going to remove nightly features, but I'd like to pick an option to
```
use the previous release of srtool (you will have to specifiy only the version and not let the srtool-actions pick it for you)
```
just for recovering current CI failures we encountered.

Which env variable should I provide to `[srtool-actions](https://github.com/chevdor/srtool-actions)` to use former version of srtool?

**Comment by chevdor** [comment]
By default, the [GHA](https://github.com/chevdor/srtool-actions) will "guess" what is the latest/canonical container image to use based on:
- [The rust version](https://github.com/paritytech/srtool/blob/master/RUSTC_VERSION)
- [the container's version](https://github.com/paritytech/srtool/blob/master/VERSION)

If you don't specify anything, it will pick `paritytech/srtool:<RUSTC_VERSION>` which is 1.69.0 currently.

To use an older version (for you that would be [`1.66.1`](https://hub.docker.com/layers/paritytech/srtool/1.66.1/images/sha256-d5e1e63d271000433cc692aef07fcff85ac5f63b6da437fc9b513bcccf287954?context=explore)), you can use the [`tag`](https://github.com/chevdor/srtool-actions/blob/master/action.yml#L28-L31) input of the GHA.

It would look like:
```
name: Srtool build using 1.66.1
on: push

jobs:
  srtool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chain: ["your_runtime"]
    steps:
      - uses: actions/checkout@v3
      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.7.0
        with:
          chain: ${{ matrix.chain }}
          runtime_dir: <path_of_your_runtime
          tag: 1.66.1                                        ⬅️⬅️⬅️ ADD THAT
      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > ${{ matrix.chain }}-srtool-digest.json
          cat ${{ matrix.chain }}-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"
```
